Revert #9354 (#9401)
# Summary

Even though initial tests passed, the inclusion of #9354 is now causing
build errors due to the following:

```text
D:\a\MonoGame\MonoGame\Tests\Framework\Graphics\GraphicsDeviceTest.cs(461,10): error CS0246: The type or namespace name 'RunOnUIAttribute' could not be found (are you missing a using directive or an assembly reference?) [D:\a\MonoGame\MonoGame\Tests\MonoGame.Tests.DesktopVK.csproj]
D:\a\MonoGame\MonoGame\Tests\Framework\Graphics\GraphicsDeviceTest.cs(461,10): error CS0246: The type or namespace name 'RunOnUI' could not be found (are you missing a using directive or an assembly reference?) [D:\a\MonoGame\MonoGame\Tests\MonoGame.Tests.DesktopVK.csproj]
```

Taking steps to revert this change

### Contributor Declaration

- [X] I certify that no LLM's were used to generate any code or
documentation in this contribution.